version: '3.8'
services:
  web:
    build:
      context: .
      args:
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        RAILS_ENV: ${RAILS_ENV}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_REGION: ${AWS_REGION}
        AWS_BUCKET: ${AWS_BUCKET}
        AWS_ENDPOINT: ${AWS_ENDPOINT}
        secret_key_base: ${secret_key_base}
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_URL=${DATABASE_URL} 
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - RAILS_ENV=${RAILS_ENV}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - aws_access_key_id=${aws_access_key_id}
      - aws_secret_access_key=${aws_secret_access_key}
      - PORT=${PORT}
      - secret_key_base=${secret_key_base}
